# Generated by Django 5.2.6 on 2025-11-04 15:11

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام آگهی")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("header", "هدر (Header)"),
                            ("main", "بنر اصلی / بالای فوتر (Main banner)"),
                            ("sidebar", "ستون چپ (Sidebar left)"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="گروه آگهی",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ads/images/",
                        verbose_name="عکس (اختیاری)",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="لینک مقصد (اختیاری)"
                    ),
                ),
                (
                    "external_code",
                    models.TextField(
                        blank=True, verbose_name="کد خارجی (HTML/JS، اختیاری)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع نمایش"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان نمایش"
                    ),
                ),
                (
                    "max_impressions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حداکثر نمایش (بار)"
                    ),
                ),
                (
                    "impressions_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="تعداد نمایش فعلی"
                    ),
                ),
                (
                    "clicks_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="تعداد کلیک\u200cها"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="به\u200cروز شده در"
                    ),
                ),
            ],
            options={
                "verbose_name": "آگهی",
                "verbose_name_plural": "آگهی\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="نام دسته\u200cبندی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="نامک (slug)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="توضیحات سئو"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FooterSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        default="خانه\u200cآذین پلتفرمی برای معرفی محصولات و نمونه\u200cکارها.",
                        verbose_name="متن درباره",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© ۱۴۰۴ خانه\u200cآذین :: طراح: عباس مهدوی",
                        max_length=255,
                        verbose_name="متن کپی\u200cرایت",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثلاً 'main' یا 'footer'",
                        max_length=100,
                        verbose_name="نام منو",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="نامک منو"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "منو",
                "verbose_name_plural": "منوها",
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="خانه\u200cآذین",
                        max_length=200,
                        verbose_name="نام سایت",
                    ),
                ),
                ("about_text", models.TextField(blank=True, verbose_name="متن درباره")),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن کپی\u200cرایت"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.CreateModel(
            name="AdClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=45,
                        verbose_name="IP کلیک\u200cکننده",
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="زمان کلیک"
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="blog.ad",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلیک آگهی",
                "verbose_name_plural": "کلیک\u200cهای آگهی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=45,
                        verbose_name="IP بازدیدکننده",
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="زمان بازدید"
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="blog.ad",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید آگهی",
                "verbose_name_plural": "بازدیدهای آگهی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان آلبوم")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="نامک (slug)",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=6,
                        null=True,
                        unique=True,
                        verbose_name="کد آلبوم",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="albums/covers/",
                        verbose_name="عکس شاخص",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "order_instructions",
                    models.TextField(blank=True, verbose_name="توضیحات سفارش"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="albums",
                        to="blog.category",
                        verbose_name="دسته\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "آلبوم",
                "verbose_name_plural": "آلبوم\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlbumImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="albums/images/", verbose_name="تصویر"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="عنوان تصویر"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.album",
                        verbose_name="آلبوم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر آلبوم",
                "verbose_name_plural": "تصاویر آلبوم",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="آدرس (URL)"
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام route"
                    ),
                ),
                (
                    "url_params",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="پارامترهای مسیر"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("show", models.BooleanField(default=True, verbose_name="نمایش")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="blog.menu",
                        verbose_name="منو",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="blog.menuitem",
                        verbose_name="والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم منو",
                "verbose_name_plural": "آیتم\u200cهای منو",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="نامک (slug)",
                    ),
                ),
                ("content", models.TextField(verbose_name="متن")),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=300, verbose_name="خلاصه"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="posts/featured/",
                        verbose_name="عکس شاخص",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=6,
                        null=True,
                        unique=True,
                        verbose_name="کد یکتا",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروز رسانی"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="blog.category",
                        verbose_name="دسته\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست",
                "verbose_name_plural": "پست\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان لینک")),
                ("url", models.CharField(max_length=500, verbose_name="نشانی (URL)")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب نمایش"
                    ),
                ),
                ("show", models.BooleanField(default=True, verbose_name="نمایش")),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_links",
                        to="blog.sitesetting",
                        verbose_name="سایت",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک فوتر",
                "verbose_name_plural": "لینک\u200cهای فوتر",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FooterIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان آیکون")),
                (
                    "image",
                    models.ImageField(upload_to="footer/icons/", verbose_name="آیکون"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="نشانی (URL)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("show", models.BooleanField(default=True, verbose_name="نمایش")),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_icons",
                        to="blog.sitesetting",
                        verbose_name="سایت",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیکون فوتر",
                "verbose_name_plural": "آیکون\u200cهای فوتر",
                "ordering": ["order"],
            },
        ),
    ]
