# Generated by Django 5.2.6 on 2025-11-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="مثلاً: 'bi bi-star-fill' برای Bootstrap Icons",
                max_length=100,
                null=True,
            ),
        ),
    ]
