# Generated by Django 5.2.6 on 2025-11-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_album_description_post_summary_alter_album_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="copyright_text",
            field=models.CharField(
                default="© ۱۴۰۴ خانه\u200cآذین",
                max_length=200,
                verbose_name="متن کپی\u200cرایت",
            ),
        ),
    ]
