# Generated by Django 5.2.6 on 2025-11-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_sitesetting_copyright_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="footericon",
            name="html",
            field=models.TextField(blank=True, verbose_name="HTML دلخواه"),
        ),
        migrations.AddField(
            model_name="footericon",
            name="icon_class",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="کلاس آیکون (مثل bootstrap)"
            ),
        ),
        migrations.AlterField(
            model_name="footericon",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="footer/icons/", verbose_name="آیکون"
            ),
        ),
    ]
