# Generated by Django 5.2.6 on 2025-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_footericon_html_footericon_icon_class_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="description",
        ),
        migrations.AlterField(
            model_name="album",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان آلبوم"),
        ),
    ]
